//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace milionerzy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historia_Gier
    {
        public int ID { get; set; }
        public string Nick { get; set; }
        public int Wynik { get; set; }
        public int Uzyte_kola { get; set; }
        public int Pytanie_koncowe { get; set; }
    }
}
