//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace milionerzy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pytania
    {
        public int Id { get; set; }
        public string Tresc { get; set; }
        public string Poprawna_odpowiedz { get; set; }
        public string Falszywa_odpowiedz_1 { get; set; }
        public string Falszywa_odpowiedz_2 { get; set; }
        public string Falszywa_odpowiedz_3 { get; set; }
    }
}
